title: "CMIP MRE Hanging Test"
description: >
  Just a test to see if we can reproduce the hanging issue with fsspec
recipes:
  - id: time_only
    object: "cmip_mre:time_only"
  - id: lon_only
    object: "cmip_mre:lon_only"
  - id: time_only_load
    object: "cmip_mre:time_only_load"
  - id: lon_only_load
    object: "cmip_mre:lon_only_load"
provenance:
  providers:
    - name: "Zenodo"
      description: "Zenodo"
      roles:
        - host
      url: https://zenodo.org/records/10261274
    - name: "TBD"
      description: "TODO"
      roles:
        - producer
        - licensor
  license: "unknown"
maintainers:
  - name: "Julius Busecke"
    orcid: 0000-0001-8571-865X
    github: jbusecke
